server:
  port: 8333

spring:
  profiles:
    active: @spring.profiles.active@
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: service-common
          uri: lb://service-common
          predicates:
            - Path=/common/** # 路径匹配
    nacos:
      discovery:
        server-addr: ${spring.nacos.address}